### PR TITLE
Add more resemblance to the original game

### PR DESCRIPTION
**Pull request by LiquidLemon**
This is mostly a cosmetic change but I think it makes the simulation more interesting.

I've fixed a few issues in collision handling and the way entities are drawn (in relation to their centers) because most of the code assumed a different model than the one present.

### CODE REVIEW

**Comment by forestbelton** [comment]
Hey! I appreciate you taking the time to make this PR. Do you think you could adapt it to be more like the approach outlined [here](https://gamedev.stackexchange.com/a/4255)? I think it will make the bouncing most Pong-like.

**Comment by LiquidLemon** [comment]
Sure, I considered taking it further but didn't know if it was wanted.

**Comment by LiquidLemon** [comment]
It's now implemented.

**Comment by forestbelton** [comment]
This is is a much-needed improvement. The game mechanics feel more natural. Great work! 👍

**Pull request merged**
